apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend
spec:
 replicas: 4
 selector:
  matchLabels:
   app: backend
 template:
  metadata:
   labels:
    app: backend
  spec:
   containers:
    - name: backend
      image: hugoamac/express-api:latest
      ports:
      - containerPort: 3000